repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.31.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [ commit ]
