// Code generated by mockery v2.42.1. DO NOT EDIT.

package user

import (
	context "context"

	errs "github.com/raffops/chat_commons/pkg/errs"
	mock "github.com/stretchr/testify/mock"

	user "github.com/raffops/chat_auth/internal/app/user/models"
)

// ReaderRepository is an autogenerated mock type for the ReaderRepository type
type ReaderRepository struct {
	mock.Mock
}

type ReaderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ReaderRepository) EXPECT() *ReaderRepository_Expecter {
	return &ReaderRepository_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function with given fields: ctx, key, value
func (_m *ReaderRepository) GetUser(ctx context.Context, key string, value interface{}) (user.User, errs.ChatError) {
	ret := _m.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 user.User
	var r1 errs.ChatError
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) (user.User, errs.ChatError)); ok {
		return rf(ctx, key, value)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) user.User); ok {
		r0 = rf(ctx, key, value)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}) errs.ChatError); ok {
		r1 = rf(ctx, key, value)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errs.ChatError)
		}
	}

	return r0, r1
}

// ReaderRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type ReaderRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
func (_e *ReaderRepository_Expecter) GetUser(ctx interface{}, key interface{}, value interface{}) *ReaderRepository_GetUser_Call {
	return &ReaderRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, key, value)}
}

func (_c *ReaderRepository_GetUser_Call) Run(run func(ctx context.Context, key string, value interface{})) *ReaderRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *ReaderRepository_GetUser_Call) Return(_a0 user.User, _a1 errs.ChatError) *ReaderRepository_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReaderRepository_GetUser_Call) RunAndReturn(run func(context.Context, string, interface{}) (user.User, errs.ChatError)) *ReaderRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, columns, filters, sorts, page
func (_m *ReaderRepository) ListUsers(ctx context.Context, columns []string, filters []user.Filter, sorts []user.Sort, page user.Pagination) ([]user.User, errs.ChatError) {
	ret := _m.Called(ctx, columns, filters, sorts, page)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []user.User
	var r1 errs.ChatError
	if rf, ok := ret.Get(0).(func(context.Context, []string, []user.Filter, []user.Sort, user.Pagination) ([]user.User, errs.ChatError)); ok {
		return rf(ctx, columns, filters, sorts, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, []user.Filter, []user.Sort, user.Pagination) []user.User); ok {
		r0 = rf(ctx, columns, filters, sorts, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, []user.Filter, []user.Sort, user.Pagination) errs.ChatError); ok {
		r1 = rf(ctx, columns, filters, sorts, page)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errs.ChatError)
		}
	}

	return r0, r1
}

// ReaderRepository_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type ReaderRepository_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - columns []string
//   - filters []user.Filter
//   - sorts []user.Sort
//   - page user.Pagination
func (_e *ReaderRepository_Expecter) ListUsers(ctx interface{}, columns interface{}, filters interface{}, sorts interface{}, page interface{}) *ReaderRepository_ListUsers_Call {
	return &ReaderRepository_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, columns, filters, sorts, page)}
}

func (_c *ReaderRepository_ListUsers_Call) Run(run func(ctx context.Context, columns []string, filters []user.Filter, sorts []user.Sort, page user.Pagination)) *ReaderRepository_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].([]user.Filter), args[3].([]user.Sort), args[4].(user.Pagination))
	})
	return _c
}

func (_c *ReaderRepository_ListUsers_Call) Return(_a0 []user.User, _a1 errs.ChatError) *ReaderRepository_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReaderRepository_ListUsers_Call) RunAndReturn(run func(context.Context, []string, []user.Filter, []user.Sort, user.Pagination) ([]user.User, errs.ChatError)) *ReaderRepository_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewReaderRepository creates a new instance of ReaderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReaderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReaderRepository {
	mock := &ReaderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
