// Code generated by mockery v2.42.1. DO NOT EDIT.

package user

import (
	context "context"

	errs "github.com/raffops/chat/pkg/errs"
	mock "github.com/stretchr/testify/mock"

	sql "database/sql"

	user "github.com/raffops/auth/internal/app/user/models"
)

// ReaderWriterRepository is an autogenerated mock type for the ReaderWriterRepository type
type ReaderWriterRepository struct {
	mock.Mock
}

type ReaderWriterRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ReaderWriterRepository) EXPECT() *ReaderWriterRepository_Expecter {
	return &ReaderWriterRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, tx, u
func (_m *ReaderWriterRepository) CreateUser(ctx context.Context, tx *sql.Tx, u user.User) (user.User, errs.ChatError) {
	ret := _m.Called(ctx, tx, u)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 user.User
	var r1 errs.ChatError
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, user.User) (user.User, errs.ChatError)); ok {
		return rf(ctx, tx, u)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, user.User) user.User); ok {
		r0 = rf(ctx, tx, u)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.Tx, user.User) errs.ChatError); ok {
		r1 = rf(ctx, tx, u)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errs.ChatError)
		}
	}

	return r0, r1
}

// ReaderWriterRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type ReaderWriterRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - u user.User
func (_e *ReaderWriterRepository_Expecter) CreateUser(ctx interface{}, tx interface{}, u interface{}) *ReaderWriterRepository_CreateUser_Call {
	return &ReaderWriterRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, tx, u)}
}

func (_c *ReaderWriterRepository_CreateUser_Call) Run(run func(ctx context.Context, tx *sql.Tx, u user.User)) *ReaderWriterRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.Tx), args[2].(user.User))
	})
	return _c
}

func (_c *ReaderWriterRepository_CreateUser_Call) Return(_a0 user.User, _a1 errs.ChatError) *ReaderWriterRepository_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReaderWriterRepository_CreateUser_Call) RunAndReturn(run func(context.Context, *sql.Tx, user.User) (user.User, errs.ChatError)) *ReaderWriterRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, tx, u
func (_m *ReaderWriterRepository) DeleteUser(ctx context.Context, tx *sql.Tx, u user.User) (user.User, errs.ChatError) {
	ret := _m.Called(ctx, tx, u)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 user.User
	var r1 errs.ChatError
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, user.User) (user.User, errs.ChatError)); ok {
		return rf(ctx, tx, u)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, user.User) user.User); ok {
		r0 = rf(ctx, tx, u)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.Tx, user.User) errs.ChatError); ok {
		r1 = rf(ctx, tx, u)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errs.ChatError)
		}
	}

	return r0, r1
}

// ReaderWriterRepository_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type ReaderWriterRepository_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - u user.User
func (_e *ReaderWriterRepository_Expecter) DeleteUser(ctx interface{}, tx interface{}, u interface{}) *ReaderWriterRepository_DeleteUser_Call {
	return &ReaderWriterRepository_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, tx, u)}
}

func (_c *ReaderWriterRepository_DeleteUser_Call) Run(run func(ctx context.Context, tx *sql.Tx, u user.User)) *ReaderWriterRepository_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.Tx), args[2].(user.User))
	})
	return _c
}

func (_c *ReaderWriterRepository_DeleteUser_Call) Return(_a0 user.User, _a1 errs.ChatError) *ReaderWriterRepository_DeleteUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReaderWriterRepository_DeleteUser_Call) RunAndReturn(run func(context.Context, *sql.Tx, user.User) (user.User, errs.ChatError)) *ReaderWriterRepository_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetDB provides a mock function with given fields:
func (_m *ReaderWriterRepository) GetDB() *sql.DB {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDB")
	}

	var r0 *sql.DB
	if rf, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}

	return r0
}

// ReaderWriterRepository_GetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDB'
type ReaderWriterRepository_GetDB_Call struct {
	*mock.Call
}

// GetDB is a helper method to define mock.On call
func (_e *ReaderWriterRepository_Expecter) GetDB() *ReaderWriterRepository_GetDB_Call {
	return &ReaderWriterRepository_GetDB_Call{Call: _e.mock.On("GetDB")}
}

func (_c *ReaderWriterRepository_GetDB_Call) Run(run func()) *ReaderWriterRepository_GetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ReaderWriterRepository_GetDB_Call) Return(_a0 *sql.DB) *ReaderWriterRepository_GetDB_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReaderWriterRepository_GetDB_Call) RunAndReturn(run func() *sql.DB) *ReaderWriterRepository_GetDB_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, key, value
func (_m *ReaderWriterRepository) GetUser(ctx context.Context, key string, value interface{}) (user.User, errs.ChatError) {
	ret := _m.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 user.User
	var r1 errs.ChatError
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) (user.User, errs.ChatError)); ok {
		return rf(ctx, key, value)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) user.User); ok {
		r0 = rf(ctx, key, value)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}) errs.ChatError); ok {
		r1 = rf(ctx, key, value)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errs.ChatError)
		}
	}

	return r0, r1
}

// ReaderWriterRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type ReaderWriterRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
func (_e *ReaderWriterRepository_Expecter) GetUser(ctx interface{}, key interface{}, value interface{}) *ReaderWriterRepository_GetUser_Call {
	return &ReaderWriterRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, key, value)}
}

func (_c *ReaderWriterRepository_GetUser_Call) Run(run func(ctx context.Context, key string, value interface{})) *ReaderWriterRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *ReaderWriterRepository_GetUser_Call) Return(_a0 user.User, _a1 errs.ChatError) *ReaderWriterRepository_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReaderWriterRepository_GetUser_Call) RunAndReturn(run func(context.Context, string, interface{}) (user.User, errs.ChatError)) *ReaderWriterRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, columns, filters, sorts, page
func (_m *ReaderWriterRepository) ListUsers(ctx context.Context, columns []string, filters []user.Filter, sorts []user.Sort, page user.Pagination) ([]user.User, errs.ChatError) {
	ret := _m.Called(ctx, columns, filters, sorts, page)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []user.User
	var r1 errs.ChatError
	if rf, ok := ret.Get(0).(func(context.Context, []string, []user.Filter, []user.Sort, user.Pagination) ([]user.User, errs.ChatError)); ok {
		return rf(ctx, columns, filters, sorts, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, []user.Filter, []user.Sort, user.Pagination) []user.User); ok {
		r0 = rf(ctx, columns, filters, sorts, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, []user.Filter, []user.Sort, user.Pagination) errs.ChatError); ok {
		r1 = rf(ctx, columns, filters, sorts, page)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errs.ChatError)
		}
	}

	return r0, r1
}

// ReaderWriterRepository_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type ReaderWriterRepository_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - columns []string
//   - filters []user.Filter
//   - sorts []user.Sort
//   - page user.Pagination
func (_e *ReaderWriterRepository_Expecter) ListUsers(ctx interface{}, columns interface{}, filters interface{}, sorts interface{}, page interface{}) *ReaderWriterRepository_ListUsers_Call {
	return &ReaderWriterRepository_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, columns, filters, sorts, page)}
}

func (_c *ReaderWriterRepository_ListUsers_Call) Run(run func(ctx context.Context, columns []string, filters []user.Filter, sorts []user.Sort, page user.Pagination)) *ReaderWriterRepository_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].([]user.Filter), args[3].([]user.Sort), args[4].(user.Pagination))
	})
	return _c
}

func (_c *ReaderWriterRepository_ListUsers_Call) Return(_a0 []user.User, _a1 errs.ChatError) *ReaderWriterRepository_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReaderWriterRepository_ListUsers_Call) RunAndReturn(run func(context.Context, []string, []user.Filter, []user.Sort, user.Pagination) ([]user.User, errs.ChatError)) *ReaderWriterRepository_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, tx, u
func (_m *ReaderWriterRepository) UpdateUser(ctx context.Context, tx *sql.Tx, u user.User) (user.User, errs.ChatError) {
	ret := _m.Called(ctx, tx, u)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 user.User
	var r1 errs.ChatError
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, user.User) (user.User, errs.ChatError)); ok {
		return rf(ctx, tx, u)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, user.User) user.User); ok {
		r0 = rf(ctx, tx, u)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.Tx, user.User) errs.ChatError); ok {
		r1 = rf(ctx, tx, u)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errs.ChatError)
		}
	}

	return r0, r1
}

// ReaderWriterRepository_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type ReaderWriterRepository_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - u user.User
func (_e *ReaderWriterRepository_Expecter) UpdateUser(ctx interface{}, tx interface{}, u interface{}) *ReaderWriterRepository_UpdateUser_Call {
	return &ReaderWriterRepository_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, tx, u)}
}

func (_c *ReaderWriterRepository_UpdateUser_Call) Run(run func(ctx context.Context, tx *sql.Tx, u user.User)) *ReaderWriterRepository_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.Tx), args[2].(user.User))
	})
	return _c
}

func (_c *ReaderWriterRepository_UpdateUser_Call) Return(_a0 user.User, _a1 errs.ChatError) *ReaderWriterRepository_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReaderWriterRepository_UpdateUser_Call) RunAndReturn(run func(context.Context, *sql.Tx, user.User) (user.User, errs.ChatError)) *ReaderWriterRepository_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewReaderWriterRepository creates a new instance of ReaderWriterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReaderWriterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReaderWriterRepository {
	mock := &ReaderWriterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
